//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repaso2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehiculo
    {
        public int Id { get; set; }
        public string marca { get; set; }
        public int precio { get; set; }
        public string foto { get; set; }
    }
}
